vich_uploader:
    db_driver: orm

    mappings:
        gift_images:
            uri_prefix: /images/gifts
            upload_destination: '%kernel.project_dir%/public/images/gifts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        list_images:
            uri_prefix: /images/lists
            upload_destination: '%kernel.project_dir%/public/images/lists'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
